Update the gitHub actions workflow and README.md
* change workflow name
* add to show postgresql.conf
* add the badge to the README.md
* and fix some codes.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: make and make installcheck for pg_rman
+name: Test with PG13
 
 on:
   push:
@@ -33,10 +33,10 @@ jobs:
         # install
         sudo apt-get update -qq
         sudo apt-get -y install bc libpam-dev libedit-dev
-        wget -q https://ftp.postgresql.org/pub/source/v13.2/postgresql-13.2.tar.gz
+        wget -q https://ftp.postgresql.org/pub/source/v${{ env.PGVERSION }}/postgresql-${{ env.PGVERSION }}.tar.gz
         tar xzf postgresql-${{ env.PGVERSION }}.tar.gz
 
-        # TODO: if master branch
+        # TODO: if test with master branch
         # git clone --single-branch --branch ${{ env.PGVERSION }} \
         #   https://github.com/postgres/postgres.git ${{ env.PGVERSION }}
 
@@ -52,9 +52,7 @@ jobs:
       shell: bash -xe {0}
       run: |
         LOGFILE=~/make.log  # TODO: though I want to remove duplicated vars...
-        grep -C 1 warning $LOGFILE
-        rm $LOGFILE
-      continue-on-error: true    # it's ok if warning doesn't exists
+        grep -C 1 warning $LOGFILE || exit 0     # ok if warning doesn't exists (= status code is 1)
 
     - name: create database directory
       shell: bash -xe {0}
@@ -72,9 +70,18 @@ jobs:
         echo "host    all         all         ::1/128               trust" >> $PGDATA/pg_hba.conf
         echo "wal_level = replica" >> $PGDATA/postgresql.conf
         echo "archive_mode = on" >> $PGDATA/postgresql.conf
-        echo "archive_command = 'cp %p ${{ env.ARCHIVEDIR }}/%f'" >> $PGDATA/postgresql.conf
+        echo "archive_command = 'cp %p $ARCHIVEDIR/%f'" >> $PGDATA/postgresql.conf
         pg_ctl -V
         pg_ctl -D $PGDATA start
+
+    - name: show postgresql configuration
+      shell: bash -xe {0}
+      run: |
+        export PGHOME=~/pgsql/${{ env.PGVERSION }}
+        export PGDATA=~/pgdata/${{ env.PGVERSION }}
+        export PATH=$PGHOME/bin:$PATH:
+        pg_config --version
+        cat $PGDATA/postgresql.conf
 
     - uses: actions/checkout@v2
 
@@ -90,9 +97,7 @@ jobs:
       shell: bash -xe {0}
       run: |
         LOGFILE=~/make.log
-        grep -C 1 warning $LOGFILE
-        rm $LOGFILE
-      continue-on-error: true     # it's ok if warning doesn't exists
+        grep -C 1 warning $LOGFILE || exit 0     # ok if warning doesn't exists (= status code is 1)
 
     - name: make installcheck
       shell: bash -xe {0}
@@ -100,3 +105,10 @@ jobs:
         export PGHOME=~/pgsql/${{ env.PGVERSION }}
         export PATH=$PGHOME/bin:$PATH:
         make installcheck
+
+    - name: show the result if the regression test failed
+      if: failure()
+      shell: bash -xe {0}
+      run: |
+        cat regression.diffs   \
+         && exit 1     # notify fail
